name: CI

on: [push]

env:
  GO111MODULE: 'on'
  DOCKER_DRIVER: overlay

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.1.0'

      - name: Install dependencies
        run: |
          yarn

      - name: Build frontend
        run: |
          CI=true yarn build

      - name: Run linter
        run: |
          yarn lint
